name: PR Check Example

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, edited]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PR Checker
        uses: chenjjiaa/pr-checker@v0.1.0
        with:
          config: .github/pr-checker.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
